[package]
name = "dojo_starter"
version = "1.8.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"

[scripts]
init-world-gen = "sozo execute dojo_starter-world_gen_manager initialize_active_world_gen_config -c 0x574f524c445f47454e5f534545445f5631 2200 2200 2200 3 3 3 --wait"
migrate = "sozo build && sozo migrate && scarb run init-world-gen"
spawn = "sozo execute dojo_starter-adventurer_manager create_adventurer -c 0x414456454e5455524552 --wait"
perf-budget = "bash ./scripts/check_perf_budgets.sh"
size-budget = "bash ./scripts/check_contract_size_budgets.sh"
budget-check = "bash ./scripts/check_perf_budgets.sh && bash ./scripts/check_contract_size_budgets.sh"

[dependencies]
dojo = "1.8.0"
starknet = "2.13.1"
# Vendored from https://github.com/credence0x/cubit at pinned revision:
# 8eacc2b1d952d6266f9725776445c7fb97453403
cubit = { path = "vendor/cubit-credence" }

[dev-dependencies]
dojo_snf_test = "1.8.0"
snforge_std = "0.51.2"
dojo_cairo_test = "1.8.0"
cairo_test = "2.13.1"


[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[tool.vendor-pins.cubit]
repository = "https://github.com/credence0x/cubit"
rev = "8eacc2b1d952d6266f9725776445c7fb97453403"
